server:
  port: 8089
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: author-service
          uri: lb://AUTHOR-SERVICE
          predicates:
            - Path=/author/**
          filters:
            - AuthenticationFilter
        - id: book-service
          uri: lb://BOOKS-SERVICE
          predicates:
            - Path=/book/**
          filters:
            - AuthenticationFilter
        - id: jwt-auth-service
          uri: lb://JWT-AUTH-SERVICE
          predicates:
            - Path=/auth/**

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
